import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('[GymOS Seed] Starting database seed...');

  // Create admin user
  const adminPasswordHash = await bcrypt.hash('Admin123!', 12);
  const admin = await prisma.user.upsert({
    where: { email: 'admin@gymos.io' },
    update: {},
    create: {
      email: 'admin@gymos.io',
      passwordHash: adminPasswordHash,
      firstName: 'Admin',
      lastName: 'GymOS',
      role: 'ADMIN',
      isActive: true,
    },
  });
  console.log('[GymOS Seed] Admin user created:', admin.email);

  // Create demo trainer
  const trainerPasswordHash = await bcrypt.hash('Trainer123!', 12);
  const trainer = await prisma.user.upsert({
    where: { email: 'trainer@gymos.io' },
    update: {},
    create: {
      email: 'trainer@gymos.io',
      passwordHash: trainerPasswordHash,
      firstName: 'Demo',
      lastName: 'Trainer',
      role: 'TRAINER',
      isActive: true,
    },
  });

  await prisma.trainerProfile.upsert({
    where: { userId: trainer.id },
    update: {},
    create: {
      userId: trainer.id,
      bio: 'Certified personal trainer with 10 years of experience in strength and conditioning.',
      specialties: ['strength', 'hypertrophy', 'weight_loss'],
      certifications: ['NASM-CPT', 'CSCS'],
      coachingStyle: 'evidence-based',
      onboardingComplete: true,
    },
  });

  await prisma.subscription.upsert({
    where: { userId: trainer.id },
    update: {},
    create: {
      userId: trainer.id,
      planType: 'TRAINER',
      status: 'ACTIVE',
      provider: 'internal',
    },
  });
  console.log('[GymOS Seed] Trainer user created:', trainer.email);

  // Create demo client
  const clientPasswordHash = await bcrypt.hash('Client123!', 12);
  const client = await prisma.user.upsert({
    where: { email: 'client@gymos.io' },
    update: {},
    create: {
      email: 'client@gymos.io',
      passwordHash: clientPasswordHash,
      firstName: 'Demo',
      lastName: 'Client',
      role: 'CLIENT',
      isActive: true,
    },
  });

  await prisma.userProfile.upsert({
    where: { userId: client.id },
    update: {},
    create: {
      userId: client.id,
      gender: 'male',
      heightCm: 178,
      currentWeightKg: 85,
      goalType: 'GAIN_MUSCLE',
      activityLevel: 'MODERATELY_ACTIVE',
      experienceLevel: 'INTERMEDIATE',
      equipmentAccess: 'COMMERCIAL_GYM',
      workoutDaysPerWeek: 4,
      preferredWorkoutDurationMinutes: 60,
      dietaryPreferences: [],
      excludedFoods: [],
      unitsPreference: 'IMPERIAL',
      onboardingComplete: true,
    },
  });

  await prisma.subscription.upsert({
    where: { userId: client.id },
    update: {},
    create: {
      userId: client.id,
      planType: 'PRO',
      status: 'ACTIVE',
      provider: 'internal',
    },
  });
  console.log('[GymOS Seed] Client user created:', client.email);

  // Seed exercises — comprehensive library
  const exercises = [
    // ── LOWER BODY ──────────────────────────────────────────────────────────
    {
      name: 'Barbell Back Squat',
      slug: 'barbell-back-squat',
      description: 'The king of lower body exercises. Targets the quads, glutes, and core.',
      primaryMuscleGroup: 'Quadriceps',
      secondaryMuscleGroups: ['Glutes', 'Hamstrings', 'Core', 'Lower Back'],
      equipment: 'Barbell',
      difficulty: 'Intermediate',
      movementPattern: 'Squat',
      tutorialSteps: ['Set up the bar on your upper traps', 'Position feet shoulder-width apart', 'Brace core and descend', 'Drive through heels to stand'],
      coachingCues: ['Chest up', 'Knees out', 'Big breath before descent', 'Drive the floor away'],
      commonMistakes: ['Caving knees', 'Forward lean', 'Heel rise', 'Shallow depth'],
      safetyNotes: ['Warm up thoroughly', 'Use a spotter for heavy loads', 'Keep back neutral'],
    },
    {
      name: 'Front Squat',
      slug: 'front-squat',
      description: 'Quad-dominant squat variation with bar held in front rack position.',
      primaryMuscleGroup: 'Quadriceps',
      secondaryMuscleGroups: ['Glutes', 'Core', 'Upper Back'],
      equipment: 'Barbell',
      difficulty: 'Advanced',
      movementPattern: 'Squat',
      tutorialSteps: ['Set bar in front rack on shoulders', 'Keep elbows high', 'Descend upright', 'Drive through heels'],
      coachingCues: ['Elbows up', 'Torso vertical', 'Knees track toes', 'Full depth'],
      commonMistakes: ['Dropping elbows', 'Forward lean', 'Wrist strain'],
      safetyNotes: ['Use wrist wraps if needed', 'Master the rack position first'],
    },
    {
      name: 'Goblet Squat',
      slug: 'goblet-squat',
      description: 'Beginner-friendly squat using a dumbbell or kettlebell held at the chest.',
      primaryMuscleGroup: 'Quadriceps',
      secondaryMuscleGroups: ['Glutes', 'Core', 'Upper Back'],
      equipment: 'Dumbbell',
      difficulty: 'Beginner',
      movementPattern: 'Squat',
      tutorialSteps: ['Hold dumbbell vertically at chest', 'Feet slightly wider than shoulder-width', 'Descend between knees', 'Drive through heels to stand'],
      coachingCues: ['Elbows inside knees at bottom', 'Chest tall', 'Hips below knees'],
      commonMistakes: ['Heels rising', 'Collapsing chest', 'Limited depth'],
      safetyNotes: ['Great teaching tool for squat mechanics'],
    },
    {
      name: 'Romanian Deadlift',
      slug: 'romanian-deadlift',
      description: 'Hip hinge movement emphasizing the hamstrings and glutes with a slight knee bend.',
      primaryMuscleGroup: 'Hamstrings',
      secondaryMuscleGroups: ['Glutes', 'Lower Back', 'Core'],
      equipment: 'Barbell',
      difficulty: 'Intermediate',
      movementPattern: 'Hip Hinge',
      tutorialSteps: ['Stand hip-width with bar', 'Slight knee bend, hinge at hips', 'Lower bar along shins', 'Squeeze glutes to rise'],
      coachingCues: ['Bar close to body', 'Feel hamstring stretch', 'Neutral spine throughout', 'Hip drive up'],
      commonMistakes: ['Rounding back', 'Squatting instead of hinging', 'Bar drifting forward'],
      safetyNotes: ['Stop range of motion before lower back rounds'],
    },
    {
      name: 'Dumbbell Romanian Deadlift',
      slug: 'dumbbell-romanian-deadlift',
      description: 'Single-implement hip hinge targeting hamstrings — accessible for all levels.',
      primaryMuscleGroup: 'Hamstrings',
      secondaryMuscleGroups: ['Glutes', 'Lower Back'],
      equipment: 'Dumbbell',
      difficulty: 'Beginner',
      movementPattern: 'Hip Hinge',
      tutorialSteps: ['Hold dumbbells in front of thighs', 'Hinge at hips, slight knee bend', 'Lower dumbbells along legs', 'Rise by driving hips forward'],
      coachingCues: ['Dumbbells stay close', 'Neutral spine', 'Hamstring stretch at bottom'],
      commonMistakes: ['Rounding spine', 'Squatting motion'],
      safetyNotes: ['Start light to learn the hinge pattern'],
    },
    {
      name: 'Leg Press',
      slug: 'leg-press',
      description: 'Machine-based quad and glute exercise with lower spinal demand.',
      primaryMuscleGroup: 'Quadriceps',
      secondaryMuscleGroups: ['Glutes', 'Hamstrings'],
      equipment: 'Machine',
      difficulty: 'Beginner',
      movementPattern: 'Squat',
      tutorialSteps: ['Adjust seat so knees are ~90° at start', 'Place feet shoulder-width on platform', 'Press plate away to near full extension', 'Return with control'],
      coachingCues: ['Do not lock knees', 'Feet flat on platform', 'Full range of motion'],
      commonMistakes: ['Locking knees', 'Feet too low (quad focus only)', 'Bouncing at bottom'],
      safetyNotes: ['Never fully lock knees under load', 'Do not round lower back off pad'],
    },
    {
      name: 'Lunge',
      slug: 'lunge',
      description: 'Unilateral lower body exercise targeting quads and glutes.',
      primaryMuscleGroup: 'Quadriceps',
      secondaryMuscleGroups: ['Glutes', 'Hamstrings', 'Core'],
      equipment: 'Bodyweight',
      difficulty: 'Beginner',
      movementPattern: 'Lunge',
      tutorialSteps: ['Stand tall', 'Step forward with one leg', 'Lower back knee toward floor', 'Push back to start'],
      coachingCues: ['Front knee over toes', 'Upright torso', 'Control the descent'],
      commonMistakes: ['Knee caving inward', 'Forward lean', 'Short step'],
      safetyNotes: ['Use a wall for balance if needed'],
    },
    {
      name: 'Bulgarian Split Squat',
      slug: 'bulgarian-split-squat',
      description: 'Rear-foot-elevated split squat for intense unilateral quad and glute training.',
      primaryMuscleGroup: 'Quadriceps',
      secondaryMuscleGroups: ['Glutes', 'Hamstrings', 'Core'],
      equipment: 'Dumbbell',
      difficulty: 'Intermediate',
      movementPattern: 'Lunge',
      tutorialSteps: ['Place rear foot on bench', 'Position front foot far enough forward', 'Lower until rear knee nearly touches ground', 'Drive through front heel to rise'],
      coachingCues: ['Torso upright', 'Front knee tracks toes', 'Drive through heel'],
      commonMistakes: ['Front foot too close', 'Torso forward lean', 'Knee cave'],
      safetyNotes: ['Use dumbbells rather than barbell initially'],
    },
    {
      name: 'Hip Thrust',
      slug: 'hip-thrust',
      description: 'Barbell glute bridge variation for maximum glute activation.',
      primaryMuscleGroup: 'Glutes',
      secondaryMuscleGroups: ['Hamstrings', 'Core'],
      equipment: 'Barbell',
      difficulty: 'Intermediate',
      movementPattern: 'Hip Hinge',
      tutorialSteps: ['Sit against bench with bar over hips', 'Plant feet flat on floor', 'Drive hips up to full extension', 'Squeeze glutes at top'],
      coachingCues: ['Full hip extension', 'Chin tucked', 'Posterior pelvic tilt at top', 'Squeeze glutes hard'],
      commonMistakes: ['Hyperextending lower back', 'Bench too high', 'Not achieving full extension'],
      safetyNotes: ['Use a barbell pad for comfort'],
    },
    {
      name: 'Leg Curl',
      slug: 'leg-curl',
      description: 'Isolation exercise for the hamstrings using a machine.',
      primaryMuscleGroup: 'Hamstrings',
      secondaryMuscleGroups: [],
      equipment: 'Machine',
      difficulty: 'Beginner',
      movementPattern: 'Isolation',
      tutorialSteps: ['Lie prone on machine', 'Hook ankles under pad', 'Curl heels toward glutes', 'Lower with control'],
      coachingCues: ['Full range of motion', 'No hip rising off pad', 'Controlled negative'],
      commonMistakes: ['Hips rising off pad', 'Momentum use', 'Partial reps'],
      safetyNotes: ['Avoid if hamstring strain present'],
    },
    {
      name: 'Leg Extension',
      slug: 'leg-extension',
      description: 'Isolation machine exercise for the quadriceps.',
      primaryMuscleGroup: 'Quadriceps',
      secondaryMuscleGroups: [],
      equipment: 'Machine',
      difficulty: 'Beginner',
      movementPattern: 'Isolation',
      tutorialSteps: ['Sit with back against pad', 'Hook shins under roller', 'Extend legs to parallel', 'Lower with control'],
      coachingCues: ['Full extension', 'Squeeze quads at top', 'Slow negative'],
      commonMistakes: ['Locking out too hard', 'Using momentum', 'Incomplete range'],
      safetyNotes: ['Can stress patellar tendon — avoid with knee issues'],
    },
    {
      name: 'Calf Raise',
      slug: 'calf-raise',
      description: 'Isolation exercise for the gastrocnemius and soleus.',
      primaryMuscleGroup: 'Calves',
      secondaryMuscleGroups: [],
      equipment: 'Machine',
      difficulty: 'Beginner',
      movementPattern: 'Isolation',
      tutorialSteps: ['Stand on calf raise machine or step edge', 'Rise onto toes fully', 'Lower heels below platform', 'Repeat'],
      coachingCues: ['Full range of motion', 'Pause at top', 'Slow eccentric'],
      commonMistakes: ['Bouncing', 'Partial range', 'Too fast'],
      safetyNotes: ['Both straight and slightly bent knee variations to hit both calf heads'],
    },

    // ── CHEST ────────────────────────────────────────────────────────────────
    {
      name: 'Bench Press',
      slug: 'bench-press',
      description: 'Classic chest exercise targeting pecs, anterior deltoids, and triceps.',
      primaryMuscleGroup: 'Chest',
      secondaryMuscleGroups: ['Triceps', 'Front Deltoids'],
      equipment: 'Barbell',
      difficulty: 'Intermediate',
      movementPattern: 'Push',
      tutorialSteps: ['Lie flat on bench', 'Grip bar slightly wider than shoulder-width', 'Lower bar to chest', 'Press to full extension'],
      coachingCues: ['Retract shoulder blades', 'Plant feet firmly', 'Control the descent', 'Full lockout at top'],
      commonMistakes: ['Bouncing bar off chest', 'Flared elbows', 'Uneven grip', 'Loose back'],
      safetyNotes: ['Always use a spotter for max attempts', 'Keep wrists straight'],
    },
    {
      name: 'Incline Bench Press',
      slug: 'incline-bench-press',
      description: 'Incline variation targeting upper chest and anterior deltoids.',
      primaryMuscleGroup: 'Chest',
      secondaryMuscleGroups: ['Front Deltoids', 'Triceps'],
      equipment: 'Barbell',
      difficulty: 'Intermediate',
      movementPattern: 'Push',
      tutorialSteps: ['Set bench to 30–45°', 'Grip bar wider than shoulder-width', 'Lower to upper chest', 'Press to lockout'],
      coachingCues: ['Shoulder blades retracted', 'Upper chest contact', 'Controlled descent'],
      commonMistakes: ['Too steep an incline', 'Flared elbows', 'Bar touching neck'],
      safetyNotes: ['Use a spotter', 'Keep incline at 45° or less to spare shoulders'],
    },
    {
      name: 'Dumbbell Fly',
      slug: 'dumbbell-fly',
      description: 'Chest isolation exercise emphasizing the pectorals through a wide arc.',
      primaryMuscleGroup: 'Chest',
      secondaryMuscleGroups: ['Front Deltoids'],
      equipment: 'Dumbbell',
      difficulty: 'Beginner',
      movementPattern: 'Isolation',
      tutorialSteps: ['Lie on bench holding dumbbells above chest', 'Lower in wide arc to chest level', 'Return in same arc squeezing chest'],
      coachingCues: ['Soft elbow bend throughout', 'Stretch at bottom', 'Squeeze at top'],
      commonMistakes: ['Locking elbows (shoulder stress)', 'Going too heavy', 'Losing arch'],
      safetyNotes: ['Never go to the point of shoulder discomfort at the bottom'],
    },
    {
      name: 'Cable Fly',
      slug: 'cable-fly',
      description: 'Cable variation of the chest fly maintaining constant tension.',
      primaryMuscleGroup: 'Chest',
      secondaryMuscleGroups: ['Front Deltoids'],
      equipment: 'Cable Machine',
      difficulty: 'Beginner',
      movementPattern: 'Isolation',
      tutorialSteps: ['Set cables at chest height', 'Stand in split stance, handles in hand', 'Sweep hands together in front of chest', 'Return with control'],
      coachingCues: ['Constant tension', 'Slight forward lean', 'Squeeze at center'],
      commonMistakes: ['Too heavy (shoulder strain)', 'Using momentum'],
      safetyNotes: ['Keep slight elbow bend to protect joints'],
    },
    {
      name: 'Push-Up',
      slug: 'push-up',
      description: 'Foundational bodyweight pressing exercise for chest, shoulders, and triceps.',
      primaryMuscleGroup: 'Chest',
      secondaryMuscleGroups: ['Triceps', 'Front Deltoids', 'Core'],
      equipment: 'Bodyweight',
      difficulty: 'Beginner',
      movementPattern: 'Push',
      tutorialSteps: ['Hands slightly wider than shoulder-width', 'Body in straight line', 'Lower chest to floor', 'Press back up'],
      coachingCues: ['Tight core', 'Elbows at 45°', 'Full range of motion', 'Squeeze chest at top'],
      commonMistakes: ['Hips sagging', 'Partial range', 'Flared elbows', 'Head dropping'],
      safetyNotes: ['Scale with knee push-ups if needed'],
    },

    // ── BACK ─────────────────────────────────────────────────────────────────
    {
      name: 'Deadlift',
      slug: 'deadlift',
      description: 'Full-body compound movement targeting the posterior chain.',
      primaryMuscleGroup: 'Hamstrings',
      secondaryMuscleGroups: ['Glutes', 'Lower Back', 'Traps', 'Core'],
      equipment: 'Barbell',
      difficulty: 'Advanced',
      movementPattern: 'Hip Hinge',
      tutorialSteps: ['Stand with bar over mid-foot', 'Hip-hinge to grip bar', 'Take slack out of bar', 'Drive hips forward to stand'],
      coachingCues: ['Bar stays over mid-foot', 'Lat engagement', 'Hip hinge not squat', 'Lock out at top'],
      commonMistakes: ['Rounding lower back', 'Bar drifting from legs', 'Hyperextending at top', 'Jerking the bar'],
      safetyNotes: ['Learn proper form before adding weight', 'Avoid if lower back pain present'],
    },
    {
      name: 'Pull-Up',
      slug: 'pull-up',
      description: 'Upper body pulling exercise targeting the lats and biceps.',
      primaryMuscleGroup: 'Latissimus Dorsi',
      secondaryMuscleGroups: ['Biceps', 'Rear Deltoids', 'Core'],
      equipment: 'Pull-up Bar',
      difficulty: 'Intermediate',
      movementPattern: 'Pull',
      tutorialSteps: ['Hang from bar with pronated grip', 'Retract scapula', 'Pull chest to bar', 'Lower with control'],
      coachingCues: ['Lead with elbows', 'Full range of motion', 'Avoid kipping', 'Squeeze at top'],
      commonMistakes: ['Partial range of motion', 'Shrugging shoulders', 'Swinging', 'Not engaging lats'],
      safetyNotes: ['Build up with assisted variations', 'Avoid if shoulder injury present'],
    },
    {
      name: 'Chin-Up',
      slug: 'chin-up',
      description: 'Supinated-grip pull-up variation with greater bicep involvement.',
      primaryMuscleGroup: 'Latissimus Dorsi',
      secondaryMuscleGroups: ['Biceps', 'Core'],
      equipment: 'Pull-up Bar',
      difficulty: 'Intermediate',
      movementPattern: 'Pull',
      tutorialSteps: ['Hang with palms facing toward you', 'Pull chin over bar', 'Lower with control'],
      coachingCues: ['Elbows close to body', 'Squeeze biceps and lats at top', 'Full hang at bottom'],
      commonMistakes: ['Kipping', 'Incomplete range', 'No full hang'],
      safetyNotes: ['Assisted machine useful for beginners'],
    },
    {
      name: 'Barbell Row',
      slug: 'barbell-row',
      description: 'Horizontal pulling compound movement for upper and mid-back thickness.',
      primaryMuscleGroup: 'Latissimus Dorsi',
      secondaryMuscleGroups: ['Rhomboids', 'Rear Deltoids', 'Biceps', 'Lower Back'],
      equipment: 'Barbell',
      difficulty: 'Intermediate',
      movementPattern: 'Pull',
      tutorialSteps: ['Hip hinge to ~45°', 'Grip bar double overhand', 'Pull bar to lower chest/navel', 'Control the descent'],
      coachingCues: ['Drive elbows back', 'Squeeze shoulder blades', 'Keep back flat', 'Bar touches body'],
      commonMistakes: ['Rounding back', 'Jerking weight', 'Too much body sway'],
      safetyNotes: ['Keep core braced to protect lower back'],
    },
    {
      name: 'Dumbbell Row',
      slug: 'dumbbell-row',
      description: 'Unilateral row for lat and mid-back development.',
      primaryMuscleGroup: 'Latissimus Dorsi',
      secondaryMuscleGroups: ['Rhomboids', 'Biceps', 'Rear Deltoids'],
      equipment: 'Dumbbell',
      difficulty: 'Beginner',
      movementPattern: 'Pull',
      tutorialSteps: ['Place knee and hand on bench for support', 'Row dumbbell to hip', 'Lower with control'],
      coachingCues: ['Elbow drives back', 'Shoulder blade retraction at top', 'Dumbbell stays close to body'],
      commonMistakes: ['Twisting torso', 'Partial range', 'Weight too heavy'],
      safetyNotes: ['Keep hips square to bench'],
    },
    {
      name: 'Lat Pulldown',
      slug: 'lat-pulldown',
      description: 'Cable machine lat exercise simulating the pull-up movement.',
      primaryMuscleGroup: 'Latissimus Dorsi',
      secondaryMuscleGroups: ['Biceps', 'Rear Deltoids'],
      equipment: 'Cable Machine',
      difficulty: 'Beginner',
      movementPattern: 'Pull',
      tutorialSteps: ['Sit with thighs under pads', 'Grip bar wider than shoulder-width', 'Pull bar to upper chest', 'Return with control'],
      coachingCues: ['Lead with elbows', 'Slight lean back', 'Bar to chin level, not behind neck'],
      commonMistakes: ['Pulling behind neck', 'Excessive lean back', 'Short range'],
      safetyNotes: ['Never pull bar behind neck'],
    },
    {
      name: 'Seated Cable Row',
      slug: 'seated-cable-row',
      description: 'Horizontal pull on cable machine for mid-back and lat development.',
      primaryMuscleGroup: 'Latissimus Dorsi',
      secondaryMuscleGroups: ['Rhomboids', 'Biceps', 'Lower Back'],
      equipment: 'Cable Machine',
      difficulty: 'Beginner',
      movementPattern: 'Pull',
      tutorialSteps: ['Sit upright on machine', 'Pull handle to lower sternum', 'Squeeze shoulder blades', 'Return with control'],
      coachingCues: ['Chest up', 'Elbows back', 'Brief pause at contraction'],
      commonMistakes: ['Rounding back', 'Leaning too far back', 'Using momentum'],
      safetyNotes: ['Keep a slight arch in lower back'],
    },

    // ── SHOULDERS ────────────────────────────────────────────────────────────
    {
      name: 'Overhead Press',
      slug: 'overhead-press',
      description: 'Vertical pressing movement for shoulder and tricep development.',
      primaryMuscleGroup: 'Deltoids',
      secondaryMuscleGroups: ['Triceps', 'Upper Chest', 'Core'],
      equipment: 'Barbell',
      difficulty: 'Intermediate',
      movementPattern: 'Push',
      tutorialSteps: ['Grip bar at shoulder-width', 'Unrack and hold at shoulders', 'Press overhead to full extension', 'Lower with control'],
      coachingCues: ['Tuck chin on press', 'Full lockout', 'Brace core throughout', 'Bar travels in straight line'],
      commonMistakes: ['Excessive lower back arch', 'Incomplete lockout', 'Bar path too far forward', 'Pressing behind neck'],
      safetyNotes: ['Avoid if shoulder impingement present', 'Warm up rotator cuff'],
    },
    {
      name: 'Dumbbell Shoulder Press',
      slug: 'dumbbell-shoulder-press',
      description: 'Seated or standing shoulder press with independent arm movement.',
      primaryMuscleGroup: 'Deltoids',
      secondaryMuscleGroups: ['Triceps'],
      equipment: 'Dumbbell',
      difficulty: 'Beginner',
      movementPattern: 'Push',
      tutorialSteps: ['Hold dumbbells at shoulder height', 'Press overhead to full extension', 'Lower with control'],
      coachingCues: ['Neutral wrist', 'Full extension', 'Core braced'],
      commonMistakes: ['Arching lower back', 'Partial range', 'Wrists caving'],
      safetyNotes: ['Seated variation reduces lower back stress'],
    },
    {
      name: 'Lateral Raise',
      slug: 'lateral-raise',
      description: 'Isolation exercise for medial deltoid development.',
      primaryMuscleGroup: 'Deltoids',
      secondaryMuscleGroups: [],
      equipment: 'Dumbbell',
      difficulty: 'Beginner',
      movementPattern: 'Isolation',
      tutorialSteps: ['Hold dumbbells at sides', 'Raise arms to shoulder height', 'Lower with control'],
      coachingCues: ['Lead with elbows', 'Slight forward lean', 'Thumb slightly down at top'],
      commonMistakes: ['Too heavy', 'Shrugging', 'Swinging'],
      safetyNotes: ['Light weight with perfect form is better than heavy sloppy reps'],
    },
    {
      name: 'Face Pull',
      slug: 'face-pull',
      description: 'Cable exercise for rear deltoids and external rotators — important for shoulder health.',
      primaryMuscleGroup: 'Deltoids',
      secondaryMuscleGroups: ['Rhomboids', 'External Rotators'],
      equipment: 'Cable Machine',
      difficulty: 'Beginner',
      movementPattern: 'Pull',
      tutorialSteps: ['Set cable at head height with rope attachment', 'Pull rope to face, flaring elbows out', 'Externally rotate at the end', 'Return with control'],
      coachingCues: ['Elbows high and wide', 'External rotation at end range', 'No lower back lean'],
      commonMistakes: ['Pulling too low', 'Not rotating externally', 'Too heavy'],
      safetyNotes: ['Excellent shoulder health exercise — include regularly'],
    },

    // ── ARMS ─────────────────────────────────────────────────────────────────
    {
      name: 'Barbell Curl',
      slug: 'barbell-curl',
      description: 'Classic bicep exercise using a barbell for maximum loading.',
      primaryMuscleGroup: 'Biceps',
      secondaryMuscleGroups: ['Forearms'],
      equipment: 'Barbell',
      difficulty: 'Beginner',
      movementPattern: 'Isolation',
      tutorialSteps: ['Stand holding bar with underhand grip', 'Curl bar to shoulder height', 'Lower with control'],
      coachingCues: ['Elbows stay at sides', 'Squeeze at top', 'Slow negative'],
      commonMistakes: ['Swinging', 'Short range of motion', 'Elbows moving forward'],
      safetyNotes: ['EZ bar can reduce wrist strain'],
    },
    {
      name: 'Dumbbell Curl',
      slug: 'dumbbell-curl',
      description: 'Unilateral bicep curl allowing supination through the movement.',
      primaryMuscleGroup: 'Biceps',
      secondaryMuscleGroups: ['Forearms'],
      equipment: 'Dumbbell',
      difficulty: 'Beginner',
      movementPattern: 'Isolation',
      tutorialSteps: ['Stand holding dumbbells at sides', 'Curl with supination', 'Squeeze at top', 'Lower with control'],
      coachingCues: ['Supinate at top', 'Elbows in', 'No swinging'],
      commonMistakes: ['No supination', 'Swinging', 'Partial reps'],
      safetyNotes: ['Alternate arms or do simultaneously'],
    },
    {
      name: 'Tricep Pushdown',
      slug: 'tricep-pushdown',
      description: 'Cable isolation exercise for the triceps.',
      primaryMuscleGroup: 'Triceps',
      secondaryMuscleGroups: [],
      equipment: 'Cable Machine',
      difficulty: 'Beginner',
      movementPattern: 'Isolation',
      tutorialSteps: ['Set high pulley with bar or rope', 'Keep elbows at sides', 'Extend arms to full lockout', 'Return with control'],
      coachingCues: ['Elbows pinned to sides', 'Full lockout', 'Lean slightly forward'],
      commonMistakes: ['Elbows flaring', 'Using shoulders/body', 'Partial extension'],
      safetyNotes: ['Rope allows natural wrist rotation'],
    },
    {
      name: 'Skull Crusher',
      slug: 'skull-crusher',
      description: 'Lying tricep extension for long head development.',
      primaryMuscleGroup: 'Triceps',
      secondaryMuscleGroups: [],
      equipment: 'Barbell',
      difficulty: 'Intermediate',
      movementPattern: 'Isolation',
      tutorialSteps: ['Lie on bench, bar over chest', 'Lower bar toward forehead by bending elbows', 'Extend back to start'],
      coachingCues: ['Keep upper arms vertical', 'Controlled descent', 'Full extension'],
      commonMistakes: ['Elbows flaring out', 'Short range', 'Too heavy'],
      safetyNotes: ['EZ bar reduces wrist stress', 'Use a spotter'],
    },
    {
      name: 'Dips',
      slug: 'dips',
      description: 'Compound bodyweight exercise for triceps and chest.',
      primaryMuscleGroup: 'Triceps',
      secondaryMuscleGroups: ['Chest', 'Front Deltoids'],
      equipment: 'Bodyweight',
      difficulty: 'Intermediate',
      movementPattern: 'Push',
      tutorialSteps: ['Grip parallel bars, arms extended', 'Lower body until upper arms are parallel', 'Press back to start'],
      coachingCues: ['Slight forward lean for chest emphasis', 'Upright for tricep emphasis', 'Full range of motion'],
      commonMistakes: ['Partial range', 'Wrists bent', 'Excessive forward lean on tricep dips'],
      safetyNotes: ['Avoid if shoulder impingement present', 'Use assisted machine if needed'],
    },

    // ── CORE ─────────────────────────────────────────────────────────────────
    {
      name: 'Plank',
      slug: 'plank',
      description: 'Isometric core stability exercise.',
      primaryMuscleGroup: 'Core',
      secondaryMuscleGroups: ['Shoulders', 'Glutes'],
      equipment: 'Bodyweight',
      difficulty: 'Beginner',
      movementPattern: 'Isometric',
      tutorialSteps: ['Forearms on floor, elbows under shoulders', 'Body in straight line', 'Hold position'],
      coachingCues: ['Squeeze glutes', 'Neutral spine', 'Don\'t hold breath'],
      commonMistakes: ['Hips too high or low', 'Holding breath', 'Head dropping'],
      safetyNotes: ['Build duration gradually'],
    },
    {
      name: 'Cable Crunch',
      slug: 'cable-crunch',
      description: 'Weighted abdominal flexion exercise using a cable machine.',
      primaryMuscleGroup: 'Core',
      secondaryMuscleGroups: [],
      equipment: 'Cable Machine',
      difficulty: 'Intermediate',
      movementPattern: 'Isolation',
      tutorialSteps: ['Kneel below high pulley with rope', 'Hold rope at sides of head', 'Flex spine downward', 'Return with control'],
      coachingCues: ['Round spine, not hip flex', 'Keep hips stationary', 'Exhale on contraction'],
      commonMistakes: ['Pulling with arms', 'Hip flexion instead of spinal flexion', 'Too heavy'],
      safetyNotes: ['Kneel on a mat for comfort'],
    },
    {
      name: 'Ab Wheel Rollout',
      slug: 'ab-wheel-rollout',
      description: 'Advanced anti-extension core exercise.',
      primaryMuscleGroup: 'Core',
      secondaryMuscleGroups: ['Shoulders', 'Lats'],
      equipment: 'Bodyweight',
      difficulty: 'Advanced',
      movementPattern: 'Isometric',
      tutorialSteps: ['Kneel holding ab wheel', 'Roll forward extending body', 'Return using core strength'],
      coachingCues: ['Squeeze core throughout', 'Don\'t let hips sag', 'Control both phases'],
      commonMistakes: ['Hips sagging', 'Using momentum back', 'Going too far too soon'],
      safetyNotes: ['Start with partial range', 'Can stress lower back if form breaks'],
    },

    // ── FULL BODY / CARDIO ────────────────────────────────────────────────────
    {
      name: 'Kettlebell Swing',
      slug: 'kettlebell-swing',
      description: 'Hip-hinge power exercise targeting posterior chain with cardiovascular benefit.',
      primaryMuscleGroup: 'Glutes',
      secondaryMuscleGroups: ['Hamstrings', 'Core', 'Shoulders'],
      equipment: 'Kettlebell',
      difficulty: 'Intermediate',
      movementPattern: 'Hip Hinge',
      tutorialSteps: ['Hike kettlebell back between legs', 'Drive hips forward explosively', 'Let bell float to chest height', 'Hinge back and repeat'],
      coachingCues: ['Hip hinge not squat', 'Glute snap at top', 'Arms relaxed', 'Lat engagement on descent'],
      commonMistakes: ['Squatting the swing', 'Arms pulling', 'Rounding lower back'],
      safetyNotes: ['Master the hip hinge before loading'],
    },
    {
      name: 'Burpee',
      slug: 'burpee',
      description: 'Full-body conditioning exercise combining a push-up and jump.',
      primaryMuscleGroup: 'Core',
      secondaryMuscleGroups: ['Chest', 'Quads', 'Shoulders', 'Glutes'],
      equipment: 'Bodyweight',
      difficulty: 'Intermediate',
      movementPattern: 'Full Body',
      tutorialSteps: ['Stand, drop to push-up position', 'Perform push-up', 'Jump feet to hands', 'Explosively jump up'],
      coachingCues: ['Keep core tight throughout', 'Land softly', 'Maintain rhythm'],
      commonMistakes: ['Sagging hips in push-up', 'No jump at top', 'Rounded back'],
      safetyNotes: ['Scale by stepping instead of jumping'],
    },
    {
      name: 'Box Jump',
      slug: 'box-jump',
      description: 'Plyometric lower body power exercise.',
      primaryMuscleGroup: 'Quadriceps',
      secondaryMuscleGroups: ['Glutes', 'Hamstrings', 'Calves'],
      equipment: 'Bodyweight',
      difficulty: 'Intermediate',
      movementPattern: 'Full Body',
      tutorialSteps: ['Stand facing box', 'Load hips and swing arms', 'Jump onto box, landing softly', 'Step down to start'],
      coachingCues: ['Soft landing — absorb through hips', 'Full extension at jump', 'Step don\'t jump down'],
      commonMistakes: ['Landing stiff-legged', 'Jumping down (shin scrape risk)', 'Too-high box'],
      safetyNotes: ['Always step down, never jump down', 'Start with low box'],
    },
  ];

  for (const exercise of exercises) {
    await prisma.exercise.upsert({
      where: { slug: exercise.slug },
      update: {},
      create: exercise,
    });
  }
  console.log(`[GymOS Seed] ${exercises.length} exercises seeded.`);

  console.log('[GymOS Seed] Seed completed successfully!');
  console.log('\nDemo accounts:');
  console.log('  Admin:   admin@gymos.io   / Admin123!');
  console.log('  Trainer: trainer@gymos.io / Trainer123!');
  console.log('  Client:  client@gymos.io  / Client123!');
}

main()
  .catch((e) => {
    console.error('[GymOS Seed] Error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
